//  This file is part of the PhotoEditor Software Development Kit.
//  Copyright (C) 2016-2017 9elements GmbH <contact@9elements.com>
//  All rights reserved.
//  Redistribution and use in source and binary forms, without
//  modification, are permitted provided that the following license agreement
//  is approved and a legal/financial contract was signed by the user.
//  The license agreement can be found under the following link:
//  https://www.photoeditorsdk.com/LICENSE.txt

#import <Foundation/Foundation.h>

// Note: Unfortunately there is no way to expose a Swift struct or enum (backed by Strings) to
// Objective-C, which is why defining this as constants in Objective-C with NS_EXTENSIBLE_STRING_ENUM
// is the best way to go for now.

typedef NSString *IMGLYAnalyticsScreenViewName NS_EXTENSIBLE_STRING_ENUM;
typedef NSString *IMGLYAnalyticsEventName NS_EXTENSIBLE_STRING_ENUM;
typedef NSString *IMGLYAnalyticsEventAttributeName NS_EXTENSIBLE_STRING_ENUM;
typedef NSString *IMGLYAnalyticsEventAttributeValue NS_EXTENSIBLE_STRING_ENUM;

#pragma mark - Screen View Constants

extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameCamera;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameEditor;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameTransform;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameFilter;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameAdjust;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameTextAdd;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameText;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameTextFont;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameTextFontColor;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameTextBackgroundColor;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameStickerAdd;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameSticker;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameStickerColor;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameFrame;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameBrush;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameBrushColor;
extern IMGLYAnalyticsScreenViewName const IMGLYAnalyticsScreenViewNameFocus;

#pragma mark - Event Constants

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameApplyChanges;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameDiscardChanges;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameCameraFlashSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameCameraPositionSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameCameraPhotoRollSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameCameraRecordingModeChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameCameraTakePhoto;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameCameraRecordVideo;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameCameraShowFilter;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameCameraHideFilter;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameFilterSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameFilterIntensityChange;

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameAutoEnhancementOn;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameAutoEnhancementOff;

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNamePhotoEditOverlayActionSelect;

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTransformCropRectChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTransformFlip;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTransformRotate;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTransformStraightenAngleChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTransformAspectRatioSelect;

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameAdjustOptionChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameAdjustValueChange;

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameStickerSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameStickerCategorySelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameStickerActionSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameStickerRectChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameStickerRotationChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameStickerColorChange;

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameFrameSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameFrameDeselect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameFrameActionSelect;

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameBrushActionSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameBrushOptionChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameBrushValueChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameBrushColorChange;

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextActionSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextEdit;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextRectChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextFontSizeChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextRotationChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextFontFullscreenEnter;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextFontFullscreenExit;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextFontSelect;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextFontColorChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameTextBackgroundColorChange;

extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameFocusFadeWidthChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameFocusBlurRadiusChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameFocusControlPointsChange;
extern IMGLYAnalyticsEventName const IMGLYAnalyticsEventNameFocusOptionChange;

#pragma mark - Event Attributes

extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameFlashMode;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameCameraPosition;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameRecordingMode;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameFilterType;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameFilterIntensity;

extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameCropRect;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameStraightenAngle;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameAspectRatio;

extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameOption;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameValue;

extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameSticker;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameStickerCategory;

extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameFont;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameColor;

extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameFrame;
extern IMGLYAnalyticsEventAttributeName const IMGLYAnalyticsEventAttributeNameAction;

extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueFlashOff;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueFlashOn;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueFlashAuto;

extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueCameraPositionFront;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueCameraPositionBack;

extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueRecordingModePhoto;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueRecordingModeVideo;

extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueAdjustOptionBrightness;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueAdjustOptionContrast;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueAdjustOptionSaturation;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueAdjustOptionClarity;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueAdjustOptionShadows;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueAdjustOptionHighlights;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueAdjustOptionExposure;

extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueActionAdd;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueActionAlignment;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueActionFlip;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueActionStraighten;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueActionUndo;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueActionRedo;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueActionBringToFront;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueActionDelete;

extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueBrushOptionSize;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueBrushOptionHardness;

extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueFocusOptionNone;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueFocusOptionLinear;
extern IMGLYAnalyticsEventAttributeValue const IMGLYAnalyticsEventAttributeValueFocusOptionRadial;
